# Generated by Django 6.0 on 2025-12-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethodConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('upi', 'UPI'), ('card', 'Credit Card'), ('debit_card', 'Debit Card'), ('wallet', 'Wallet')], max_length=20, unique=True)),
                ('surcharge_percent', models.DecimalField(decimal_places=2, default=0, help_text='Extra % charged on order total for this payment method.', max_digits=5)),
            ],
        ),
    ]
