# Generated by Django 6.0 on 2025-12-17 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_order_payment_method_order_payment_surcharge_amount_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethodconfig',
            name='surcharge_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_transaction_id', models.CharField(db_index=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phonepe_transaction_id', models.CharField(blank=True, help_text='PhonePe providerReferenceId or transactionId', max_length=128)),
                ('raw_initiate_response', models.JSONField(blank=True, null=True)),
                ('raw_status_response', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('completed', 'Completed'), ('failed', 'Failed'), ('pending', 'Pending')], default='initiated', max_length=20)),
                ('payment_state', models.CharField(blank=True, help_text='PhonePe data.state or paymentState', max_length=50)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='adminapp.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
