# Generated by Django 6.0 on 2025-12-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('upi', 'UPI'), ('card', 'Credit Card'), ('debit_card', 'Debit Card'), ('wallet', 'Wallet')], default='upi', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_surcharge_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_surcharge_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
